"""add banned column to users

Revision ID: 4bdac3ae259f
Revises: f33003a13212
Create Date: 2026-08-18 15:45:09.506945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bdac3ae259f'
down_revision: Union[str, Sequence[str], None] = 'f33003a13212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to false; dropped after, since
    # the ORM-side default (models.User.banned) governs new inserts.
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'banned', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banned')
    # ### end Alembic commands ###
