"""add accent_color column to users

Revision ID: 6a240705bb45
Revises: 4fffef66392b
Create Date: 2026-08-18 21:36:17.001094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a240705bb45'
down_revision: Union[str, Sequence[str], None] = '4fffef66392b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('accent_color', sa.String(), nullable=False, server_default='notion-blue')
    )
    op.alter_column('users', 'accent_color', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accent_color')
    # ### end Alembic commands ###
