"""add plan column to users

Revision ID: f33003a13212
Revises: b1a856bfbb31
Create Date: 2026-08-18 15:16:44.149287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33003a13212'
down_revision: Union[str, Sequence[str], None] = 'b1a856bfbb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to "free"; dropped after, since
    # the ORM-side default (models.User.plan) is what governs new inserts.
    op.add_column('users', sa.Column('plan', sa.String(), nullable=False, server_default='free'))
    op.alter_column('users', 'plan', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
