"""add trial_used column to users

Revision ID: fa450ee1258c
Revises: 4bdac3ae259f
Create Date: 2026-08-18 18:24:37.693249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa450ee1258c'
down_revision: Union[str, Sequence[str], None] = '4bdac3ae259f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('trial_used', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('users', 'trial_used', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_used')
    # ### end Alembic commands ###
